export const GET_PRICES = '/prices/GET_PRICES';
export const SET_PRICES = '/prices/SET_PRICES';
export const INSERT_PRICES = '/prices/INSERT_PRICES';
export const SELECT_PRICES = '/prices/SELECT_PRICES';
export const DELETE_PRICES = '/prices/DELETE_PRICES';
export const UPDATE_PRICES = '/prices/UPDATE_PRICES';
export const ACTIVEDESACTIVE_PRICES = '/prices/ACTIVEDESACTIVE_PRICES';
export const SET_PRICES_REFRESH = '/prices/SET_PRICES_REFRESH';

export default {
	GET_PRICES,
	SET_PRICES,
	INSERT_PRICES,
	SELECT_PRICES,
	DELETE_PRICES,
	ACTIVEDESACTIVE_PRICES,
	SET_PRICES_REFRESH
};