export const GET_MODULATION = '/merchant/GET_MODULATION';
export const SET_MODULATION = '/merchant/SET_MODULATION';
export const INSERT_MODULATION = '/merchant/INSERT_MODULATION';
export const DELETE_MODULATION = '/merchant/DELETE_MODULATION';
export const UPDATE_MODULATION = '/merchant/UPDATE_MODULATION';
export const SELECT = '/merchant/SELECT';
export const REFRESH = '/merchant/REFRESH';
export const ACTIVEORDESACTIVE_MODULATION = '/merchant/ACTIVEORDESACTIVE_MODULATION';
export const SET_MODULATION_REFRESH = '/merchant/SET_MODULATION_REFRESH';


export default {
	GET_MODULATION,
	SET_MODULATION,
	INSERT_MODULATION,
	DELETE_MODULATION,
	UPDATE_MODULATION,
	SELECT,
	REFRESH,
	ACTIVEORDESACTIVE_MODULATION,
	SET_MODULATION_REFRESH
}