export const GET_AMOUNTS = '/amounts/GET_AMOUNTS';
export const SET_AMOUNTS = '/amounts/SET_AMOUNTS';
export const INSERT_AMOUNTS = '/amounts/INSERT_AMOUNTS';
export const SELECT_AMOUNTS = '/amounts/SELECT_AMOUNTS';
export const DELETE_AMOUNTS = '/amounts/DELETE_AMOUNTS';
export const UPDATE_AMOUNTS = '/amounts/UPDATE_AMOUNTS';
export const ACTIVEDESACTIVE_AMOUNTS = '/amounts/ACTIVEDESACTIVE_AMOUNTS';
export const SET_AMOUNTS_REFRESH = '/amounts/SET_AMOUNTS_REFRESH';

export default {
	GET_AMOUNTS,
	SET_AMOUNTS,
	INSERT_AMOUNTS,
	SELECT_AMOUNTS,
	UPDATE_AMOUNTS,
	ACTIVEDESACTIVE_AMOUNTS,
	SET_AMOUNTS_REFRESH
};