export const GET_CONTRACTS = '/contracts/GET_CONTRACTS';
export const SET_CONTRACTS = '/contracts/SET_CONTRACTS';
export const INSERT_CONTRACTS = '/contracts/INSERT_CONTRACTS';
export const SELECT_CONTRACTS = '/contracts/SELECT_CONTRACTS';
export const DELETE_CONTRACTS = '/contracts/DELETE_CONTRACTS';
export const UPDATE_CONTRACTS = '/contracts/UPDATE_CONTRACTS';
export const ACTIVEDESACTIVE_CONTRACTS = '/contracts/ACTIVEDESACTIVE_CONTRACTS';
export const SET_CONTRACTS_REFRESH = '/contracts/SET_CONTRACTS_REFRESH';

export default {
	GET_CONTRACTS,
	SET_CONTRACTS,
	INSERT_CONTRACTS,
	SELECT_CONTRACTS,
	DELETE_CONTRACTS,
	ACTIVEDESACTIVE_CONTRACTS,
	SET_CONTRACTS_REFRESH
};