export const GET_OPERATION_SEG = '/operation-seg/GET_OPERATION_SEG';
export const SET_OPERATION_SEG = '/operation-seg/SET_OPERATION_SEG';
export const INSERT_OPERATION_SEG = '/operation-seg/INSERT_OPERATION_SEG';
export const DELETE_OPERATION_SEG = '/operation-seg/DELETE_OPERATION_SEG';
export const UPDATE_OPERATION_SEG = '/operation-seg/UPDATE_OPERATION_SEG';
export const SELECT = '/operation-seg/SELECT';
export const REFRESH = '/operation-seg/REFRESH';
export const ACTIVEORDESACTIVE_SEG = '/operation-seg/ACTIVEORDESACTIVE_SEG';
export const SET_SEGMENT_REFRESH = '/operation-seg/SET_SEGMENT_REFRESH';


export default {
	GET_OPERATION_SEG,
	SET_OPERATION_SEG,
	INSERT_OPERATION_SEG,
	DELETE_OPERATION_SEG,
	UPDATE_OPERATION_SEG,
	SELECT,
	REFRESH,
	ACTIVEORDESACTIVE_SEG,
	SET_SEGMENT_REFRESH
}