export const GET_BUSINESS_GROUP = '/bussinessGroup/GET_BUSINESS_GROUP';
export const SET_BUSINESS_GROUP = '/bussinessGroup/SET_BUSINESS_GROUP';
export const INSERT_BUSINESS_GROUP = '/bussinessGroup/INSERT_BUSINESS_GROUP';
export const SELECT_BUSINESS_GROUP = '/bussinessGroup/SELECT_BUSINESS_GROUP';
export const DELETE_BUSINESS_GROUP = '/bussinessGroup/DELETE_BUSINESS_GROUP';
export const UPDATE_BUSINESS_GROUP = '/bussinessGroup/UPDATE_BUSINESS_GROUP';
export const ACTIVEDESACTIVE_BUSINESS_GROUP = '/bussinessGroup/ACTIVEDESACTIVE_BUSINESS_GROUP';
export const SET_BUSINESS_REFRESH = '/bussinessGroup/SET_BUSINESS_REFRESH';

export default {
	GET_BUSINESS_GROUP,
	SET_BUSINESS_GROUP,
	INSERT_BUSINESS_GROUP,
	SELECT_BUSINESS_GROUP,
	UPDATE_BUSINESS_GROUP,
	ACTIVEDESACTIVE_BUSINESS_GROUP,
	SET_BUSINESS_REFRESH
};