export const GET_BOND_CONTRACT_CLIENT = '/bond/GET_BOND_CONTRACT_CLIENT';
export const SET_BOND_CONTRACT_CLIENT = '/bond/SET_BOND_CONTRACT_CLIENT';
export const INSERT_BOND_CONTRACT_CLIENT = '/bond/INSERT_BOND_CONTRACT_CLIENT';
export const SELECT_BOND_CONTRACT_CLIENT = '/bond/SELECT_BOND_CONTRACT_CLIENT';
export const DELETE_BOND_CONTRACT_CLIENT = '/bond/DELETE_BOND_CONTRACT_CLIENT';
export const UPDATE_BOND_CONTRACT_CLIENT = '/bond/UPDATE_BOND_CONTRACT_CLIENT';
export const ACTIVEDESACTIVE_BOND_CONTRACT_CLIENT = '/bond/ACTIVEDESACTIVE_BOND_CONTRACT_CLIENT';
export const SET_BOND_REFRESH = '/bond/SET_BOND_REFRESH';

export default {
	GET_BOND_CONTRACT_CLIENT,
	SET_BOND_CONTRACT_CLIENT,
	INSERT_BOND_CONTRACT_CLIENT,
	SELECT_BOND_CONTRACT_CLIENT,
	UPDATE_BOND_CONTRACT_CLIENT,
	ACTIVEDESACTIVE_BOND_CONTRACT_CLIENT,
	SET_BOND_REFRESH
};