export const GET_MERCHANT_ENERGY = '/merchant/GET_MERCHANT_ENERGY';
export const SET_MERCHANT_ENERGY = '/merchant/SET_MERCHANT_ENERGY';
export const INSERT_MERCHANT_ENERGY = '/merchant/INSERT_MERCHANT_ENERGY';
export const DELETE_MERCHANT_ENERGY = '/merchant/DELETE_MERCHANT_ENERGY';
export const UPDATE_MERCHANT_ENERGY = '/merchant/UPDATE_MERCHANT_ENERGY';
export const SELECT = '/merchant/SELECT';
export const REFRESH = '/merchant/REFRESH';
export const ACTIVEORDESACTIVE_MERCH = '/merchant/ACTIVEORDESACTIVE_MERCHANT';
export const SET_MERCH_REFRESH = '/merchant/SET_MERCHANT_REFRESH';


export default {
	GET_MERCHANT_ENERGY,
	SET_MERCHANT_ENERGY,
	INSERT_MERCHANT_ENERGY,
	DELETE_MERCHANT_ENERGY,
	UPDATE_MERCHANT_ENERGY,
	SELECT,
	REFRESH,
	ACTIVEORDESACTIVE_MERCH,
	SET_MERCH_REFRESH
}